import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";

import "./globals.css";
import Header from "@/components/Header";

const spaceGrotesk = Space_Grotesk({
    variable: "--font-space-grotesk",
    display: "swap",
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700"],
    preload: true,
});
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html
            lang="en"

        >
            <body className={`${spaceGrotesk.variable} antialiased`}>
                <Header />

                {children}
            </body>
        </html>
    );
}
